commit 3

diff --git a/.github/workflows/monitor-dev.yaml b/.github/workflows/monitor-dev.yaml
--- a/.github/workflows/monitor-dev.yaml
+++ b/.github/workflows/monitor-dev.yaml
@@ -17,11 +17,11 @@ jobs:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
-    - name: Step is going to pass
-      run: echo Passing step
+    # - name: Step is going to pass
+    #   run: echo Passing step
       
-    - name: Step is going to fail
-      run: exit 1
+    # - name: Step is going to fail
+    #   run: exit 1
 
     - name: Report Failure to Slack
       if: ${{ failure() }}
